config/routes.rb
Askacountry::Application.routes.draw do
  get "password_resets/new"

  
  root :to => 'home#index'
  
  match 'about' => "home#about", :via => :get, :as => :about
  match 'shuffle' => "home#shuffle", :via => :get, :as => :shuffle
  
  match 'countries' => "home#countries", :via => :get
  
  resources :user_sessions, :only => [:create]
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match '/auth/:provider/callback' => "authorizations#create"
  match '/auth/failure'  => "authorizations#failure"
  match '/auth/:provider'  => "authorizations#blank"
  
  resources :password_resets
  
  resources :answerables, :only => [:create, :update] do
    member do
      get 'comments'
    end
  end
  
  resources :comments, :only => [:create, :destroy]
  
  resources :users, :except => [:new, :index]
  
  match 'signup'  => "users#new", :as => :signup

  resources :countries, :path => '', :only => [:show] do
    member do
      post 'watch', 'unwatch'
    end

    resources :askables, :path => '', :except => [:index] do
      member do
        get 'original', 'comments'
        post 'follow', 'unfollow'
      end
    end
  end
end

app/models/askable.rb
class QuestionMarkValidator < ActiveModel::Validator
  def validate(record)
     unless record.body.present? && ( record.body.include?('?') || record.body.include?('？') )
      record.errors[:body] << "should have at least one question mark"
    end
  end
end

class Askable < ActiveRecord::Base
  scope :polls, where(:type => 'Poll')
  scope :questions, where(:type => 'Question')
  
  scope :featured, where(:featured => true)
  
  attr_accessible :user_id, :body, :coverage, :country_code, :description, :yes, :no, :auto_translated
  
  after_create :log_event

  validates_presence_of :user_id, :country_code, :coverage

  validates :body,
    :uniqueness => { :scope => :country_code, :message => 'is duplicated' },
    :length => {
      :minimum => 5,
      :maximum => 300,
      :too_long => 'is too long - leave the detail to the description'
    }
    
  validates_length_of :yes, :no, 
    :minimum => 1,
    :maximum => 80,
    :if => Proc.new{|a| a.type == "Poll" }
  
  validates :coverage, :inclusion => { :in => 0..2 }
  validates_with QuestionMarkValidator

  has_many    :followings, :as      => :followable, :dependent => :destroy
  has_many    :followers,  :through => :followings, :source => :user
  
  has_many    :answerables

  belongs_to  :country,   :foreign_key => "country_code",     :primary_key => "code",     :counter_cache => true
  belongs_to  :user
  
  has_many    :events, :dependent => :destroy
  
  translates :slug, :body, :yes, :no, :description, :auto_translated, :versioning => true 
  extend FriendlyId
  friendly_id :body, :use => [:globalize, :history]
  
  acts_as_translateable
  acts_as_commentable
  
  Complex_Number = 15
  
  def normalize_friendly_id(string)
    string[0..79].slugged
  end
  
  def more_askables(limit = 4)
    Askable.includes(:translations)
      .where('askable_translations.locale = ? AND country_code = ? AND askables.id != ?', I18n.locale, self.country_code, self.id)
      .order("RAND()")
      .limit(limit)
  end
  
  private
  def log_event
    # when a user creates an askable
    self.events.create(
      :kind => self.type.downcase,
      :user_id => self.user_id,
      :country_code => self.country_code,
      :locales => I18n.locale.to_s
    )
  end
end

app/controllers/askables_controller.rb
class AskablesController < ApplicationController
  before_filter :get_country, :except => [:new, :create]
  before_filter :get_askable, :except => [:new, :create]
  before_filter :set_return_to, :only => [:follow, :unfollow]
  before_filter :require_user, :except => [:show, :original, :comments]

  def new
    @askable = Askable.new(:yes => I18n.t('ans_yes'), :no => I18n.t('ans_no'))
    @country = Country.find(params[:country_id]) if params[:country_id].present?
  end

  def create
    type = params[:askable].delete(:type)
    
    if %w(Poll Question).include?(type)
      @askable = type.constantize.new(params[:askable])
      
      @askable.user_id = current_user.id
      @askable.body.capital_first!
      @askable.yes.capital_first! unless @askable.yes.blank?
      @askable.no.capital_first! unless @askable.no.blank?
      
      @country = Country.find_by_code(@askable.country_code)
      
      if @askable.save
        flash[:notice] = t('notice.askable_created', country_name: @country.to_s)

        redirect_to country_askable_path(@country, @askable) and return false
      end
    else
      flash[:alert] = I18n.t('notice.askable_type_missing')
    end
    
    render :new
  end

  def update
    if @askable.should_update?(params[:askable])
      @askable.attributes = params[:askable].delete_if {|k, v| k == 'country_code'}
      
      if @askable.valid?
        flag = @askable.auto_translated
        
        # Auto-translated askable gets improved by user, set flag
        @askable.auto_translated = false if flag.present? && flag.to_i > 0
        
        @askable.save!
        
        @askable.translate_on_update if flag.nil? # Askable is original, check if it needs auto translation
      else
        submit_error
      end
    else
      @no_update = true
    end
  end

  def show
    if request.path != country_askable_path(@country, @askable)
      redirect_to country_askable_path(@country, @askable), status: :moved_permanently and return
    end
    
    @orig_lang, @langs = @askable.available_langs
    
    current_uid = current_user.present? ? current_user.id : 0
  
    @complex, @is_end = @askable.answer_complex(current_uid, params[:last_answerable])
    
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  def original
    @translation = @askable.translations.first
    
    @lang = @translation.locale
  end
  
  def comments
    @comments = @askable.root_comments.order('created_at DESC').page params[:page]
  end
  
  def follow
    current_user.follow(@askable)
  end

  def unfollow
    current_user.unfollow(@askable)

    render 'askables/follow'
  end

  private
  def get_askable
    begin
      @askable = Askable.find(params[:id])
      
      raise 'not available for this country' if @askable.country_code != @country.code
    rescue
      page_404
    end
  end

  def set_return_to
    @return_to = country_askable_path(@country, @askable)
  end
end

app/helpers/askable_helper.rb
module AskableHelper
  def new_askable_validation_error
    error_messages = []
    
    if @askable.errors[:country_code].present?
      error_messages << 'Please select a country to ask the question. ' 
    else
      @askable.errors.messages.each do |e|
        if e[1].present?
          if (e[0] == 'yes' || e[0] == 'no')
            error_messages << "#{e[0].to_s.capitalize} #{e[1][0]}." 
          else
            error_messages << "Question #{e[0].to_s} #{e[1][0]}."
          end
        end
      end
    end

    return error_messages
  end
  
  def askable_coverage_info(coverage, country)
    img =  (t "askable.coverage")[coverage][:img]
    name = (t "askable.coverage")[coverage][:name]
    
    str = "<img src ='/assets/#{ img }' />#{ name }"
    
    title = (t "askable.coverage")[coverage][:title]

    return content_tag(:span, str.html_safe, :title => title)
  end
  
  def owner_of?(obj)
    current_user == obj.user
  end
  
  def can_edit?(obj)
    owner_of?(obj) && obj.auto_translated.nil?
  end
  
  def can_improve?(obj)
    obj.auto_translated.present?
  end
end

app/views/askables/_answer_block.html.haml
%a(href='javascript:void(0)' onclick='aac.toggle_answerable()')
  - case @answerable.type
  - when 'Ballot'
  
    - if @answerable.new_record?
      .table.vote.new    
        .cell= t('askable.show.atv')
    - else
      - vote_class, vote =  @answerable.vote > 0 ? ['yes', @askable.yes] : ['no', @askable.no]
      .table.vote.update(class='#{ vote_class }')
        .cell= t('askable.show.edit_vote', vote: truncate(vote, :separator => ' '))
          
  - when 'Answer'
    - if @answerable.new_record?
      .table.answer.new
        .cell= t('askable.show.ata')
    - else
      .table.answer.update
        .cell= t('askable.show.edit_answer')


      

app/views/askables/_answer_comments.html.haml
- answerable ||= @commentable

.comments(class='#{ (answerable.vote > 0 ? "yes" : "no") unless answerable.vote.blank? }' id='comment_#{answerable.id}')
  .actions<
    = link_to 'Like', '#'
    
    = link_to_function t('plural.comment', count: answerable.comment_threads.size), "aac.ans_comments($(this))", class: 'scs'
    
    %span.others
      - if false
        = link_to t('share'), '#'
    
      - if answerable.auto_translated.nil?
        = link_to_if(current_user == answerable.user, t('edit'), "javascript: aac.toggle_edit_answerable(#{answerable.id});", class: 'edit') {|name| ''}
      - else
        = link_to_function t('askable.show.improve'), "aac.toggle_edit_answerable(#{answerable.id})", class: 'it'
    
  .detail
    .form
      - comment = answerable.comment_threads.new
      = render 'comments/form', :comment => comment
      
    - @comments = answerable.root_comments.order('created_at DESC').page(1)
    = render 'answerables/comments'

app/views/askables/_answer_form.html.haml
= form_for answerable, :as => 'answerable', :url => url, :remote => true do |f|
  %h2 What is your answer?
  .answer
    = f.text_area :body

  .submit
    = f.hidden_field :country_code, :value => @country.code
    = f.hidden_field :askable_id, :value => @askable.id
    
    = f.submit t('submit')
    = link_to_function t('cancel'), 'aac.toggle_answerable()'

app/views/askables/_answerable.html.haml
#answerable.blinder
  .wrapper
    - unless @answerable.new_record?
      = render "askables/#{ @answerable.type.downcase }_form", :answerable => @answerable, :url => answerable_path(@answerable)

    - else
      - if current_user.blank?
        %h2.msg 
          Your account info is required here. Please
          %a(href='/login?return_to=#{request.path}') log in
          first.
  
      - elsif current_user.can_answer?(@askable)
        = render "#{ @answerable.type.downcase }_form", :answerable => @answerable, :url => answerables_path
  
      - else
        .msg
          You cannot answer the question because the creator expects the answers
          %strong
            only
          from the people
          %strong
            who are
            = @askable.coverage == 1 ? " from #{@country}." : " not from #{@country}."
            
          %p
            You may want to
            %ul
              %li
                = link_to 'follow the question', '#'
                to keep updated
              %li
                create
                = link_to 'a similar question', '#'
              %li
                check your country of residence in
                = link_to 'your profile', user_path(current_user)

app/views/askables/_askable_answers.html.haml
#answers
  %h2.page
    .text
      - if @complex.blank?
        - #TODO promoting answer/ballots here
      - else
        = t 'plural.people_answered', count: @askable.answerables.size
    
    - if false && @askable.is_a?(Poll) && @askable.answerables.size > 10
      - yes_pc = (@askable.ballots.yes.size.to_f/@askable.ballots.size.to_f)*100

      #gauge
        .table
          .yes.cell(style='width: #{ '%.1f' % yes_pc }%')
            %em #{ '%.1f' % yes_pc }%

          .no.cell
            %em #{ '%.1f' % (100 - yes_pc) }%
  
  = render 'complex'

app/views/askables/_body.html.haml
%h1.question.yesno
  %span.lang= t("language.code.#{ @lang }").upcase
  
  %span(class = '#{ @askable.is_a?(Poll) && @askable.or_negative? ? "yes" : "none" }')
    = @translation.body
    
  - if @askable.is_a?(Poll) && !@askable.simple?
    - unless @askable.or_negative?
      %span(class="yes")= @translation.yes
    %em or
    %span(class="no") #{ @translation.no }?

app/views/askables/_complex.html.haml
- @complex.each do |c|
  - if c.kind_of?(Hash) # the complex item is a list of voters
    = render 'complex_list', :item => c
  - else
    = render 'complex_item', :answerable => c

- last_answerable = @complex.last.kind_of?(Hash) ? @complex.last.values[0].last : @complex.last

- unless @is_end
  .lmv= link_to I18n.t('askable.show.more'), country_askable_path(@country, @askable, :last_answerable => last_answerable.id), :remote => true

app/views/askables/_complex_list.html.haml
.answerable(class='#{ item.keys[0] > 0 ? "yes" : "no" }')
  .answerer
    - item.values[0].each do |v|
      %span= user_small_avatar_link(v.user)
    %span.info>= time_ago_in_words(item.values[0].last.updated_at)
    / voted affirmatively

app/views/askables/_question.html.haml
- @orig_lang ||= @askable.translations.first.locale

.question
  .header
    %h1.yesno
      %span(class = '#{ @askable.is_a?(Poll) && @askable.or_negative? ? "yes" : "" }')
        = @askable.body
        
      - if @askable.is_a?(Poll) && !@askable.simple?
        - unless @askable.or_negative?
          %span.yes= @askable.yes
        %em= t('or')
        %span.no<= @askable.no
        ?

    - unless @askable.description.blank?
      .desc= @askable.description
    
  - if can_edit?(@askable) || can_improve?(@askable)
    .edit
      = form_for @askable, as: 'askable', remote: true, url: country_askable_path(@country, @askable) do |f|
        = f.hidden_field :country_code, :value => @country.code
        
        - unless @orig_lang == I18n.locale
          .orig
            - I18n.with_locale(@orig_lang) do
              %h1
                = @askable.body
                
              - if @askable.is_a?(Poll)
                .yesno
                  %span.yes= @askable.yes
                  %em= t('or')
                  %span.no= @askable.no
                  
        .body= f.text_area :body
        
        - if @askable.is_a?(Poll)
          .table.yesno
            .cell.yes= f.text_field :yes, class: 'field'
            %span.or= t('or')
            .cell.no= f.text_field :no, class: 'field'
            
        - unless @orig_lang == I18n.locale
          - orig_desc = I18n.with_locale(@orig_lang) { @askable.description }
          .orig.desc
            - if orig_desc.blank?
              = t('askable.show.orig_desc_empty')
            - else
              = orig_desc

        .text= f.text_area :description

        .submit(class='#{ @orig_lang == I18n.locale ? "" : "low" }')
          - unless @orig_lang == I18n.locale
            .orig.legend
              #{ t('askable.show.is_orig') }:
              = t("language.#{ @orig_lang }")
          = f.submit t('done')
          = link_to_function t('cancel'), 'aac.toggle_edit_askable()'

app/views/askables/new.html.haml
- content_for :js do
  = javascript_include_tag 'askable_new'

- content_for :title_string do
  #{ @country.to_s if @country.present? } + New Question

- flash.now[:alert]  = new_askable_validation_error if  @askable.errors.present?


#nask
  %h1
    = t('askable.new.country_h1', country: @country.to_s)
    = country_image(@country, 'm')
    
  %h2.sub
    %em= t('askable.new.choose')
  
  .types
    #Poll.type.active
      .block
        %h2 Simple Polling
        .intro
          .q
            .left Q:
            .dashes
            .qmark ?
          .a
            %span.yesno 
              %span.yes Yes 
              %em or
              %span.no No?
          .pie
            .left A:
            = image_tag('/assets/pie.png')

    
    #Question.type.inactive
      .block
        %h2 Classic Q&A
        .intro
          .q
            .left Q:
            .dashes
            .qmark ?
          .a 
            .left A:
            .dots
            .dots
            .dots

    .or or
          
        
  .askable
    = form_for @askable, :url => country_askables_path(@country) do |f|
      .form
        %table
          = f.hidden_field :type, :value => 'Poll'
          = f.hidden_field :country_code, :value => (@country.present? ? @country.code : nil)
        
          %tr.q
            %td.label= f.label "Question: "
            %td.text= f.text_area :body

          %tr.yesno
            %td.label Answers:
            %td
              = f.text_field :yes, :class => 'field'
              %em or
              = f.text_field :no, :class => 'field'
    
          %tr.desc.vague
            %td.label 
              Description: 
            %td.text= f.text_area :description
    
          %tr.coverage
            %td.label Participation:
            %td= f.select :coverage, [["Anyone", 0], ["Only those who are from the country", 1], ["Only those who are *not* from the country", 2]]
              
      .submit
        %a(href='#{ country_path(@country) }')
          &larr; back to #{ @country.to_s }
        = f.submit t('submit')

app/views/askables/question.html.haml
- title = "Ask #{@country.name}"

- content_for :title_string do
  = title + ": " + @askable.body.truncate(80, :separator => ' ')

- content_for :js do
  = javascript_include_tag 'askable'

- if current_user
  - @answerable = @askable.answerables.where(country_code: @country.code, user_id: current_user.id).first
  - @is_owner = (current_user == @askable.owner)

#spbody
  #sph
    %h4.info
      .user
        = user_country_flag_link @askable.owner, :title => "#{@askable.owner} is from #{@askable.owner.country}"
        is asking #{link_to @country, country_path(@country)}:
    .poll
      .flag= link_to (country_image @country, 'o', :size => '50x50'), country_path(@country)
    
      %h1.question
        %span
          = best_in_place_if @is_owner, @askable, :body, :type => :textarea, :ok_button => 'OK', :path => country_askable_path(@country, @askable), :classes => 'update_question_success', :data => { :country => @country.slug }

    .lc    
      - if @is_owner && @askable.description.present?
        .desc= best_in_place @askable, :description, :type => :textarea, :ok_button => 'OK', :path => country_askable_path(@country, @askable), :nil => 'add description...', :classes => 'update_desc_success'
      - elsif @is_owner
        .add_desc= best_in_place @askable, :description, :type => :textarea, :nil => 'add description...', :ok_button => 'OK', :path => country_askable_path(@country, @askable), :classes => 'update_desc_success'
      - elsif @askable.description.present?
        .desc= @askable.description

      .comments_head
        = best_in_place_if @is_owner, @askable, :coverage, :display_with => :poll_coverage_info, :helper_options => { :country => @country }, :type => :select, :collection => poll_coverage_data(@askable.coverage, @country), :path => country_askable_path(@country, @askable)

        %span.sep
          |
        = link_to_function pluralize(@askable.comment_threads.size, 'comment'), '$("#askable_comments .detail").show("blind")', :id => 'ltpcs'

      = render 'askable_comments'

  #spb
    .rc  
      %ul
        #follow= render 'follow'
      
        Share to
        %li.share= link_to 'Facebook', '#'
        %li.share= link_to 'Twitter', '#'
        %li.share= link_to 'Google', '#'
    
      .polls
        %h3 More Questions
        - askables = @askable.more_askables
      
        %ul
          - askables.each do |a|
            %li= link_to a, country_askable_path(@country, a)
    .lc
      #ballots
        - if @complex.blank?
          %h2 Waiting for 10 people's votes
        - else
          %h2 #{ @askable.ballots.size } people have voted

          = render 'complex'
  


              

app/views/askables/show.html.haml
- if current_user
  - @answerable = @askable.answerables.where(country_code: @country.code, user_id: current_user.id).first 

- @answerable ||= @askable.is_a?(Poll) ? Ballot.new(vote: 0) : Answer.new

- content_for :title_string do
  #{ t 'country_title', :country_name => @country.to_s }:
  = @askable.body.truncate(80, :separator => ' ')

- content_for :js do
  = javascript_include_tag 'askable'

- if false  # disable ellipse collapse feature
  :css
    .ellips:after {
      content: "#{ t('askable.show.css.expand')}";
    }

#spbody
  .statuses
    .user.status.active
      = t('askable.show.created', link: user_country_flag_link(@askable.user)).html_safe
    
    - unless @orig_lang == I18n.locale
      .status
        = t('askable.show.original')
        %a.link(href='#{ original_country_askable_path(@country, @askable) }' data-remote=true)
          %span.lang= t("language.code.#{ @orig_lang }").upcase
          %span.text= t("language.#{ @orig_lang }")
  
  #sph
    .flag
      %a(href='#{ country_path(@country) }' title='#{ @country.to_s }')
        = country_image @country, 'l', :size => '60x60'
    .blocks
      = render 'follow'
      .table.share
        .cell
          &#8618;
          = t 'askable.show.share'
          %a(href='#')<
            = image_tag '/assets/twitter.png'
          %a(href='#')
            = image_tag '/assets/facebook.png'
    
      = render 'answer_block'
    
    = render 'question'
        
    .actions
      %span.coverage
        = askable_coverage_info(@askable.coverage, @country)
    
      - if @orig_lang == I18n.locale
        - unless @langs.blank?
          %span.translation(title='#{t("askable.show.is_orig_title")}')
            %span.lang= t("language.code.#{ @orig_lang }").upcase
            = t('askable.show.is_orig')
          
          - if false
            %span.availables
              = image_tag '/assets/translation.png'
              = t('askable.show.available')
              - @langs.each do |l|
                %a(href='#')= t("language.code.#{ l }")
        
      - else
        %span.translation(title='#{ t("askable.show.t_from_to", to: t("language.#{ I18n.locale }"), from: t("language.#{ @orig_lang }"))}')
          %span.lang<
            = t("language.code.#{ @askable.translation.locale }").upcase
          - if @askable.auto_translated.to_i > 0
            = t('askable.show.auto')
          - else
            = t('askable.show.translator')
            = user_avatar_link(User.find(@askable.translation.versions.last.whodunnit), size: '18x18')


      %span.others
        %span.comments
          %a#ltac(href='#' onclick='aac.toggle_comments(); return false;')<
            = image_tag '/assets/comment.png'
            = t 'plural.comment', count: @askable.comment_threads.size
        
        - if can_edit?(@askable)
          %span.edit
            %a(href='#' onclick='aac.toggle_edit_askable(); return false;')<
              = image_tag '/assets/edit.png'
              = t('edit')
      
        - if can_improve?(@askable)
          %span.translate
            = link_to_function t('askable.show.improve'), 'aac.toggle_edit_askable()'

  = render 'askable_comments'
  = render 'answerable'
  
  #spb
    .rc
      - askables = @askable.more_askables
      
      - unless askables.blank?
        %h3 More questions
    
        %ul
          - askables.each do |a|
            %li= link_to a, country_askable_path(@country, a)
      
      - versions = Version.where('item_type = ? AND whodunnit is not null', 'Askable::Translation').where(item_id: @askable.translations.collect {|t| t.id}).group('whodunnit')
      - if versions.present? && versions.size.size > 1
        %h3.page Contributors
        .contrib
          - versions.each do |v|
            = user_small_avatar_link(User.find(v.whodunnit))
        
      
      %h3
        Return to
        = link_to @country.to_s, country_path(@country)

    .lc
      = render "askable_answers"
            

app/views/askables/show.js.erb
div = $("<div><%= escape_javascript(render 'askables/complex') %></div>").hide();
$('#answers .lmv').replaceWith(div);
div.slideDown();

app/views/askables/update.js.erb
div = $("<%= j (render 'question') %>").hide();
$('#sph .question').replaceWith(div);
$('#sph .question, #sph .actions').fadeIn('fast');

<% if @no_update %>
  aac.notify('notice', '<%= t("notice.no_update") %>')
<% elsif @askable.auto_translated.nil? %>
  aac.notify('notice', '<%= t("notice.askable_updated") %>')
<% else %>
  aac.notify('notice', '<%= t("notice.translation_updated") %>')
<% end %>