config/routes.rb
Askacountry::Application.routes.draw do
  get "password_resets/new"

  
  root :to => 'home#index'
  
  match 'about' => "home#about", :via => :get, :as => :about
  match 'shuffle' => "home#shuffle", :via => :get, :as => :shuffle
  
  match 'countries' => "home#countries", :via => :get
  
  resources :user_sessions, :only => [:create]
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match '/auth/:provider/callback' => "authorizations#create"
  match '/auth/failure'  => "authorizations#failure"
  match '/auth/:provider'  => "authorizations#blank"
  
  resources :password_resets
  
  resources :answerables, :only => [:create, :update] do
    member do
      get 'comments'
    end
  end
  
  resources :comments, :only => [:create, :destroy]
  
  resources :users, :except => [:new, :index]
  
  match 'signup'  => "users#new", :as => :signup

  resources :countries, :path => '', :only => [:show] do
    member do
      post 'watch', 'unwatch'
    end

    resources :askables, :path => '', :except => [:index] do
      member do
        get 'original', 'comments'
        post 'follow', 'unfollow'
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password_confirmation

  attr_accessible :first_name, :last_name, :email, :country_code, :password, :password_confirmation, :avatar

  before_save :process_names

  belongs_to :country,              :foreign_key => 'country_code',     :primary_key => 'code'
  has_many :authorizations,         :dependent => :destroy

  has_many :followings,             :dependent => :destroy
  has_many :watching_countries,     :through => :followings,            :source => :followable, :source_type => 'Country', :order => 'followings.updated_at DESC'
  has_many :following_askables,     :through => :followings,            :source => :followable, :source_type => 'Askable'

  has_many :askables
  has_many :answerables,            :dependent => :destroy
  has_many :answered_askables,      :through => :answerables,           :source => :askable

  has_many :events

  acts_as_authentic do |c|
    c.ignore_blank_passwords = true #ignoring passwords
    c.validate_password_field = false #ignoring validations for password fields
    c.merge_validates_format_of_email_field_options :message => 'does not look like an email address'
  end

  acts_as_voter

  presence_msg = 'is required'

  validates_presence_of :first_name, :email, :message => presence_msg
  validates_uniqueness_of :email

  # there is no need to verify password for a new record
  # but only for changing password
  validate do |user|
    user.errors.add(:password, presence_msg) if user.password.blank?
    user.errors.add(:password, "should have at least 6 characters") if (user.password.present? && user.password.length < 6)
    unless user.new_record?
      user.errors.add(:password_confirmation, presence_msg) if user.password_confirmation.blank?
      user.errors.add(:password, "and confirmation must match") if user.password != user.password_confirmation
    end
  end

  mount_uploader :avatar, AvatarUploader

  def self.build_from_info(info, country_code)
    User.new(:first_name => info.name[0], :last_name => info.name[1], :email => info.email, :country_code => country_code)
  end

  def deliver_password_reset_instructions!
    reset_perishable_token!
    UserMailer.password_reset(self).deliver
  end

  def is_admin?
    self.admin
  end

  def name
    self.last_name.present? ? self.first_name + " #{self.last_name.capitalize}" : self.first_name
  end

  alias_method :to_s, :name

  #********************************************
  #
  #   Business Logic
  #
  #********************************************

  def lives_in?(country)
    self.country_code == (country.class == Country ? country.code : country)
  end

  def following?(followable)
    self.followings.where(:followable_id => followable.id, :followable_type => get_follow_type(followable)).present?
  end

  def follow(followable)
    self.followings.create!(:followable => followable)
  end

  def unfollow(followable)
    f = self.followings.where(:followable_id => followable.id, :followable_type => get_follow_type(followable))
    f.first.destroy
  end

  def can_answer?(askable)
    case askable.coverage
    when 0 then return true
    when 1 then return self.lives_in?(askable.country_code)
    when 2 then return !self.lives_in?(askable.country_code)
    end
  end

  private
  def process_names
    #TODO: setting up unique id for permalinks here
  end

  def get_follow_type(followable)
    followable.kind_of?(Askable) ? 'Askable' : followable.class.name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # require 'UserInfo'

  def new
    @info = session[:info]
    # session[:info] = nil
    
    if @info.present?
      @user = User.build_from_info(@info, country_code_from_request)

      render :new_auth
    else
      @user = User.new
      UserSessionsController.new
    end
  end

  def create
    @info = session[:info]
    session[:info] = nil

    @user = User.new(params[:user])
    @user.country_code = country_code_from_request
    
    #TODO: test below block
    if @user.save
      @user.authorizations.create!(
        :provider => @info.provider,
        :uid  => @info.uid,
        :token => @info.token,
        :link => @info.link
      ) if @info.present?
      
      flash[:notice] = "Sign up successful!"
      redirect_to root_url
    else
      render (@info.blank? ? :new : :new_auth)
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])

    if @user.save
      flash[:notice] = "Successfully updated profile."
      redirect_to :action => "show"
    else
      render :show
    end
  end

  def destroy
  end
end

app/helpers/user_helper.rb
module UserHelper
  def signup_validation_error
    error_messages = []

    @user.errors.messages.each do |e|
      error_messages << "#{e[0].to_s.capitalize.sub('_', ' ')} #{e[1][0]}." if e[1].present?
    end

    return error_messages
  end

  def user_country_flag_link(user, cur = nil, options = {})
    u, i = (cur == user) ? ['You', ''] : [user.to_s, user_country_image(user, options)]
    
    link_to "#{u}#{i}".html_safe, user_path(user)
  end

  def user_country_image(u, options = {})
    image_tag "/assets/flags/#{u.country_code}.png", options
  end
  
  def user_avatar_link(u, options = {})
    link_to image_tag(u.avatar_url(:thumb), options), user_path(u)
  end
  
  def user_small_avatar_link(u, options = {})
    link_to image_tag(u.avatar_url(:thumb), :size => '24x24'), user_path(u)
  end
end

app/views/users/_edit.html.haml
= form_for @user, :url => user_path(@user), :method => :put, :html => {:multipart => true} do |f|
  %p
    = f.label_text_field :first_name, "First name: " 
    = f.label_text_field :last_name, "Last name: "
  
  %p
    =f.label_text_field :email, "Email: "
  
  %p
    =f.label_password_field :password, "New Password: ", :value => ""
  
  %p
    =f.label_password_field :password_confirmation, "Password Confirmation: "
  
  %p
    = f.label :avatar, "Your new look: "
    = f.file_field :avatar

  %p
    =f.submit "Update"

app/views/users/home.html.haml
#uh
  .lc
    %h2 Recent Activities
    .feed_list
      - @events.each do |e|
        .feed= render "events/#{e.kind}", :event => e, :show_country => true

app/views/users/new.html.haml
- content_for :title_string do
  = 'Sign up Ask a Country'

- content_for :js do
  = javascript_include_tag 'home'

- flash.now[:alert] = signup_validation_error if @user.errors.present?


#signup.home
  %h1 Sign up
  
  .holder
    = render 'user_sessions/links'
    
    .email
      %strong.or
        or
        = link_to_function 'sign up with email', 'aac.toggle_login_form()'
      
      .form(style='#{ "display: none" unless  @user.errors.present? }')
        = form_for @user do |f|
          .wrapper
            = f.text_field :email, :tabindex => 1
            = f.label :email, 'Your Email', class: 'placeholder'
    
          .wrapper
            = f.text_field :first_name, :tabindex => 2
            = f.label :first_name, 'First(display) name', class: 'placeholder'
          
            .wrapper
              = f.text_field :last_name, :tabindex => 3
              = f.label :last_name, 'Last name(optional)', class: 'placeholder'
  
          .wrapper
            = f.password_field :password , :tabindex => 4
            = f.label :password, "Password", class: 'placeholder'
  

          .submit= f.submit "Sign up", :tabindex => 5
    
    .reminder
      Have an account already? #{ link_to 'Log in here', login_path }.

app/views/users/new_auth.html.haml
- title = "Log in with #{@info.provider.capitalize}"

- content_for :title_string do
  = title

#confirm.home
  %h1 Confirm your account
  
  .holder
    .form
      = form_for @user do |f|
        .avatar
          = image_tag @info.image
          %br
          = link_to_function 'change it', '#'
          = f.file_field :avatar, :value => @info.image, :tabindex => 4
        
        .wrapper
          = f.label :email, "Email: "
          .stroke= f.text_field :email, :tabindex => 1
    
        #flnames.wrapper
          %table
            %tr
              %td
                = f.label :first_name, "First name:"
                .stroke= f.text_field :first_name, :tabindex => 2
              %td.optional
                = f.label :last_name, "Last name:"
                .stroke= f.text_field :last_name, :tabindex => 3
              
          .submit= f.submit "Save", :tabindex => 5

app/views/users/show.html.haml
- @is_owner = (@user == current_user)

- content_for :js do
  = javascript_include_tag 'user' if @is_owner

#suh
  #avatar= image_tag(@user.avatar_url)
  %h2= @user.name

#suw.su
  %h2 Watching
  .hlocs
    - countries = @user.watching_countries
    - countries.each do |c|
      %a(href="/#{c.slug}")
        .c
          = image_tag "/assets/flags/#{c.code}-o.png"
          %br 
          %span= c

#sua.su
  %h4 Asking
  .polls
    - askings = @user.askables
    - askings.each do |a|
      .poll= link_to a, country_askable_path(a.country, a)


#suv.su
  %h4 Voted
  .polls
    - voted = @user.answered_askables
    - voted.each do |v|
      .poll= link_to v, country_askable_path(v.country, v)

#suf.su
  %h4 Following
  .polls
    - followings = @user.following_askables
    - followings.each do |f|
      .poll= link_to f, country_askable_path(f.country, f)



%h2 Profile

%table#edits
  %tr
    %td 
      %span#fnl First Name: 
    %td= @user.first_name

  %tr
    %td
      %span#lnl Last Name: 
    %td= @user.last_name



%p
  home country: #{@user.country}

- if @is_owner  
  = render 'edit'
    
%h2 
  Recent Activities
%ul
  %li Added a question for China: blah blah blah
  %li Voted for "No" on the question for United States: blah blah