config/routes.rb
Askacountry::Application.routes.draw do
  get "password_resets/new"

  
  root :to => 'home#index'
  
  match 'about' => "home#about", :via => :get, :as => :about
  match 'shuffle' => "home#shuffle", :via => :get, :as => :shuffle
  
  match 'countries' => "home#countries", :via => :get
  
  resources :user_sessions, :only => [:create]
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match '/auth/:provider/callback' => "authorizations#create"
  match '/auth/failure'  => "authorizations#failure"
  match '/auth/:provider'  => "authorizations#blank"
  
  resources :password_resets
  
  resources :answerables, :only => [:create, :update] do
    member do
      get 'comments'
    end
  end
  
  resources :comments, :only => [:create, :destroy]
  
  resources :users, :except => [:new, :index]
  
  match 'signup'  => "users#new", :as => :signup

  resources :countries, :path => '', :only => [:show] do
    member do
      post 'watch', 'unwatch'
    end

    resources :askables, :path => '', :except => [:index] do
      member do
        get 'original', 'comments'
        post 'follow', 'unfollow'
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @country = current_user.country

      countries = [@country.code]
      countries.concat(current_user.watching_countries.map(&:code))

      askables = current_user.following_askables.map(&:id)

      @events = Event.where('locales LIKE ?', "%#{ I18n.locale.to_s }%")
                      .where('country_code in (?) or askable_id in (?)', countries, askables)
                      .order('created_at DESC')

      render 'users/home'
    else
      @country = Country.find_by_code(country_code_from_request)

      shuffle_poll
    end
  end

  def about

  end

  def shuffle
    shuffle_poll

    respond_to do |format|
      format.js
    end
  end

  def countries
    @countries = Country.where(:code => %w(us cn))
    @countries << nil # separater between popolar and all countries
    @countries.concat(Country.where('country_translations.locale = ?', I18n.locale).includes(:translations))

    respond_to do |format|
      format.js
    end
  end

  private
  def shuffle_poll
    cond = '1 = 1'
    cond.concat(' and id NOT in (?)') unless session[:shuffled_polls].blank?

    pool = Poll.featured.where(cond, session[:shuffled_polls])

    if pool.blank?
      session[:shuffled_polls] = nil

      @poll = Poll.featured.sample
    else
      @poll = pool.sample
    end

    session[:shuffled_polls] ||= Array.new
    session[:shuffled_polls] << @poll.id
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def search_list_item(c)
    "'#{c.code}': { 'code': '#{c.code}', 'name': \"#{c.to_s}\", 'lookup': \"#{c.lookup_string}\", 'slug': '#{c.slug}'}".html_safe
  end
end

app/views/home/_poll.html.haml
- yes_pc = ((poll.ballots.yes.size.to_f/poll.ballots.size.to_f)*100).to_i
      
.poll
  .flag
    .c= country_image poll.country, 'l', :size => '50x50', :title => poll.country.to_s
    .shuffle= link_to image_tag('/assets/shuffle.png'), shuffle_path, :title => 'Shuffle for a random question', :remote => true
  %a(href="#{country_askable_path(poll.country, poll)}")
    %h2.q= poll.body
    .table
      .yes.cell(style='width: #{ yes_pc }%')
        %span &ldquo;#{ poll.yes }&rdquo;
        %em #{ yes_pc }%

      .or.cell
      .no.cell
        %span &ldquo;#{ poll.no }&rdquo;
        %em #{ 100 - yes_pc }%

app/views/home/about.html.haml
%h1 About Us

%h2 Service
%p The way we know about other countries is old. We came across stories in Int' sections on newspaper. From time to time, news channels roll out appalling scenes or absurd stories about some remote country. We could not help but wondered is it really what is going on over there and what the people there really think? 

%p Askacountry.com is the place where people can ask question to people from other countries and get the answer. The prejudice from race difference and country borders is so obsolete in the time of Internet. Our vision is to help people in the world understand each other.


%h2 Team
%p
  We are a small team of developers and designers from an #{link_to 'authoritarian country', 'https://en.wikipedia.org/wiki/Authoritarianism'}.

%h2 Anonymity
%p The team chooses to stay anonymous. We believe good questions are of most importance to Askacountry.com and good questions for our own country always means embarrassment to the government. It censors the Internet and banned a lot of websites, inc. Goolge, Twitter and Facbook, and they persecute those who made them look bad, which is personal experience for some of us. Instead of self-censorship and living in fear, we chose to hide our identities and be free.

app/views/home/countries.js.erb
<% last = @countries.pop %>

var countries = {
  <% @countries.each do |c| %>
    <% if c.blank? # separater between popolar and all countries %>
      'empty': {},
    <% else %>
      <%= search_list_item(c) %>,
    <% end %>
  <% end %>
    <%= search_list_item(last) %>
}

app/views/home/index.html.haml
- content_for :js do
  = javascript_include_tag 'home'

- @contenter_class = @actioner_class = 'homer'

- content_for :actioner do
  #hh1
    %h1
      Ask a country anything
      %span
        in close-ended questions

  #hcs
    .side
      .or or
      .search.ui-widget
        %input(value="Go to another country")
    / .flags
    /   - count = 0
    /   - availables = Country.available
    /   - availables.shuffle.each do |c|
    /     .flag(id='c_#{ count }')
    /       = home_country_flag(c)
    /       .content
    /         %h2= c.to_s
    /         - if c.full_name.present?
    /           .info
    /             = c.full_name
    /         .stats
    /           claimed by
    /           = link_to 'jeremy Y.', '#'
    /           and now have
    /           %span= c.askables.size
    /           questions and
    /           %span= c.answerables.size
    /           answers
    / 
    /         .enter
    /           %a(href='#{ country_path(c) }')
    /             Enter &rarr;
    /     - count += 1
    /   - nas = Country.where(:code => Candidate_Countries)
    /   - nas.concat(Country.unavailable.where('code not in (?)', Candidate_Countries).order("RAND()").limit(7))
    /   - nas.pop and nas << @country if !availables.include?(@country) && !nas.include?(@country)
    / 
    /   - nas.shuffle.each do |n|
    /     .flag(id='c_#{ count }')
    /       = home_country_flag(n, true)
    /       .content
    /         %h2= n.to_s
    /         - if n.full_name.present?
    /           .info
    /             = n.full_name
    /         %div Full access is not active yet. You can &ldquo;claim&rdquo; the country and activate all features by the first new question accepted.
    /         .enter
    /           %a(href='#{ country_path(n) }')
    /             Find Out More &rarr;
    /     - count += 1

#h2head
  %h1 
    %span ...and help us
    find the answer of the people

  = render 'home/poll', :poll => @poll

app/views/home/shuffle.js.erb
div = $("<%= (j (render 'home/poll', :poll => @poll)).html_safe %>")
div.hide()

$("#h2head .poll").replaceWith(div)

div.fadeIn()