config/routes.rb
Askacountry::Application.routes.draw do
  get "password_resets/new"

  
  root :to => 'home#index'
  
  match 'about' => "home#about", :via => :get, :as => :about
  match 'shuffle' => "home#shuffle", :via => :get, :as => :shuffle
  
  match 'countries' => "home#countries", :via => :get
  
  resources :user_sessions, :only => [:create]
  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  match '/auth/:provider/callback' => "authorizations#create"
  match '/auth/failure'  => "authorizations#failure"
  match '/auth/:provider'  => "authorizations#blank"
  
  resources :password_resets
  
  resources :answerables, :only => [:create, :update] do
    member do
      get 'comments'
    end
  end
  
  resources :comments, :only => [:create, :destroy]
  
  resources :users, :except => [:new, :index]
  
  match 'signup'  => "users#new", :as => :signup

  resources :countries, :path => '', :only => [:show] do
    member do
      post 'watch', 'unwatch'
    end

    resources :askables, :path => '', :except => [:index] do
      member do
        get 'original', 'comments'
        post 'follow', 'unfollow'
      end
    end
  end
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  generalize_credentials_error_messages "Your account information is not vaild."
end

app/controllers/user_session_controller.rb
class UserSessionController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy

  def new
    @user_session = UserSession.new
  end

  def create    
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default root_url
    else
      render :action => :new
    end    
  end
  
  def destroy
    current_user_session.destroy
    flash[:notice] = "Logout successful!"
    redirect_back_or_default root_url
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_no_user, :only => [:new, :create]
  before_filter :require_user, :only => :destroy
  
  def new
    @user_session = UserSession.new(remember_me: true)
    
    session[:return_to] = params[:return_to] if params[:return_to].present?
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      flash[:notice] = "Login successful!"
      redirect_back_or_default root_url
    else
      render :action => :new
    end    
  end
  
  def destroy
    current_user_session.destroy
    clear_shuffled_polls
    flash[:notice] = "You have logged out."
    redirect_back_or_default root_url
  end
end

app/helpers/user_session_helper.rb
module UserSessionHelper
  def login_validation_error
    if @user_session.errors[:base].present?
      error_message = @user_session.errors[:base][0]
      @user_session.errors[:email] = @user_session.errors[:password] = ['just to fire up error display for email field']
    else
      e = @user_session.errors.messages.first

      error_message = "#{e[0].capitalize} #{e[1][0]}." if e[1].present?
    end
    
    return error_message
  end
end

app/views/user_sessions/_links.html.haml
%h2= t('home.login.one_click')
.links
  %p= link_to image_tag('/assets/facebook_login.png'), '/auth/facebook', class: 'auth', :'data-width' => 660, :'data-height' => 420
  %p= link_to image_tag('/assets/twitter_login.png'), '/auth/twitter', class: 'auth', :'data-width' => 900, :'data-height' => 700

app/views/user_sessions/new.html.haml
- content_for :title_string do
  = 'Log in to Ask a Country'

- content_for :js do
  = javascript_include_tag 'home'

- flash.now[:alert]  = login_validation_error if @user_session.errors.present?

#login.home
  %h1
    %span= t('login')
  
  .holder
    = render 'links'    
    
    .email      
      %strong.or<
        = t('or1') 
        = link_to_function t('home.login.with_email'), 'aac.toggle_login_form()'
      
      .form(style='#{ "display: none" unless  @user_session.errors.present? }')
        = form_for @user_session do |f|
          .wrapper
            = f.text_field :email, tabindex: 1
            = f.label :email, t('home.login.your_email'), class: 'placeholder'
    
          .forgot= link_to t('home.login.forgot'), password_resets_path
          .wrapper
            = f.password_field :password, tabindex: 2
            = f.label :password, t('home.login.password'), class: 'placeholder'
    
          .remember
            = f.check_box :remember_me, tabindex: 3
            = f.label :remember_me, t('home.login.remember')
          .submit
            = f.submit t('login'), tabindex: 4
          
    .reminder
      = t('home.login.dont_have')
      = link_to t('home.login.now'), signup_path